package com.mario;
/*
 * This source file was generated by the Gradle 'init' task
 */
import org.junit.jupiter.api.Test;
// import static org.junit.jupiter.api.Assertions.*;
// import org.junit.Test;

import com.mario.MainTest;


class MainTest {
    @Test 
    public void verifyNoExceptionThrown() {
        
    }
}
