/*
 * This source file was generated by the Gradle 'init' task
 */
package com.snake;

import org.junit.jupiter.api.Test;
// import static org.junit.jupiter.api.Assertions.*;
// import org.junit.Test;


class MainTest {
    @Test 
    public void verifyNoExceptionThrown() {
        Main.main(new String[]{});
    }
}
